version: '2'
services:
  web:
    build: .
    ports:
      - "8069:8069"
    container_name: benandfrank-odoo
    volumes:
      - ./openacademy:/home/myosusr/openacademy-repo/openacademy
      - ./webservices:/home/myosusr/openacademy-repo/webservices
      - ./.odoorc:/home/myosusr/.odoorc
